### PR TITLE
Ignore ephemeral NFS files

### LINKED ISSUE #67: java.nio.file.NoSuchFileException due to .nfs* files?
I am using `fs-store` on an NFS volume, and am getting (partial) stacktraces similar to
```
java.nio.file.NoSuchFileException: /nfs/.nfsbe549e9e950952130000002b
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
at java.nio.channels.FileChannel.open(FileChannel.java:287)
at java.nio.channels.FileChannel.open(FileChannel.java:335)
at konserve.filestore$migrate_file_v1.invokeStatic(filestore.clj:409)
at konserve.filestore$migrate_file_v1.invoke(filestore.clj:398)
at konserve.filestore$migrate_in_list_keys.invokeStatic(filestore.clj:552)
at konserve.filestore$migrate_in_list_keys.invoke(filestore.clj:550)
at konserve.impl.default$list_keys.invokeStatic(default.cljc:229)
at konserve.impl.default$list_keys.invoke(default.cljc:225)
at konserve.impl.default.DefaultStore._keys(default.cljc:426)
at konserve.core$keys.invokeStatic(core.cljc:281)
at konserve.core$keys.invoke(core.cljc:275)
<my application code>
```
In `filestore.clj`, it looks like `list-files` does no filtering, unlike for example `count-konserve-keys`, which filters for `.ksv` files. I wonder if `list-files` may be seeing temporary `.nfs*` files (in case you're not familiar: http://nfs.sourceforge.net/#faq_d2) that, by the time they are later referenced, no longer exist; and whether perhaps filtering out files `konserve` should not care about (if that's possible to define) earlier might avoid this.

I am working with `0.6.0-SNAPSHOT` due to issue #60 opened by my colleague. (Specifically, `0.6.0-20211004.084316-6` -- I tried the latest `0.6.0-SNAPSHOT` and got `clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: key-vec in this context, compiling:(konserve/filestore.clj:640:25)`, just FYI.)

Thanks in advance for any thoughts you might have.

### PR DESCRIPTION
**Pull request by pmspire**
Meant to fix #67. `clojure -M:test -m kaocha.runner` reports 0 failures.

### CODE REVIEW

File: src/konserve/filestore.clj [hunk 1]
```diff
@@ -67,8 +67,9 @@
   "Lists all files on the first level of a directory."
   (let [root (Paths/get directory (into-array String []))
         ds (Files/newDirectoryStream root)
+        ephemeral? (fn [^Path path] (starts-with? (.getFileName path) ".nfs"))
```
Comment (pmspire) [inline src/konserve/filestore.clj:70]: This could be extended to ignore other kinds of temporary files that `konserve` should not care about.

Comment (whilo) [reply src/konserve/filestore.clj:70]: Yes, I think it would be good to at least lift the `ephemeral?` predicate to a function argument with your predicate as default. Maybe even better would be a dynamic binding for it, sidestepping the need to lift the argument all up to the surface API.

**Review by whilo — APPROVED** [review]
Good work, but I indeed would prefer it to be extensible.

File: src/konserve/filestore.clj (hunk 1 above)
Comment (pmspire) [reply src/konserve/filestore.clj]: I updated to define and use a dynamic predicate function. Please let me know if you had something else in mind.

I also switched to matching ephemeral files based on regex instead of prefix, for more flexibility; and added a (currently single-element) vector to make an obvious place for adding patterns if needed. I wonder if "ephemeral" might be too limiting a name, but it could be changed if a broader use case appears.

Comment (whilo) [reply src/konserve/filestore.clj]: Nice work! Sorry for changing my mind again, but I think best would be to actually add `ephemeral?` as a field to the `BackingStore` with your implementation as default value here: 

https://github.com/replikativ/konserve/blob/development/src/konserve/filestore.clj#L690

And then just pass `ephemeral?` to `list-files` as an additional argument in the `-keys` protocol implementation of the `BackingStore` here:

https://github.com/replikativ/konserve/blob/development/src/konserve/filestore.clj#L137

Does this make sense?

Comment (pmspire) [reply src/konserve/filestore.clj]: I think so. Please see the latest diff. I made `list-files` multi-arity, taking `ephemeral?` as an argument in the arity-2 case (so that e.g. `count-konserve-keys` still works as before, making an arity-1 call to `list-files`, as it does its own filtering on `.ksv` filename extensions), and wired up the previous implementation of `ephemeral?` a `BackingFilestore` field. Tests pass.

Comment (whilo) [reply src/konserve/filestore.clj]: Yes, this is exactly what I meant, thank you! The only thing missing that would be nice is to allow passing in of `ephemeral?` as a keyword argument with your function as default value to `connect-fs-store`.

Comment (pmspire) [reply src/konserve/filestore.clj]: `ephemeral?` is now an optional keyword argument to `connect-fs-store`, with a default implementation. I was able to pass in alternate lambdas to e.g. filter all or no files.

Comment (whilo) [reply src/konserve/filestore.clj]: Perfect! Thank you!
